### ISSUE TITLE
Workflow #3: Desktop Installation for Developers and access to Private Resources

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare_on_jupyter#16]
Workflow #3:  Desktop = install everything from scratch.  start from a HydroShare link, move files back and forth from your computer to HydroShare.

Readme:  Why do you recommend Yarn?  If we assume that the new user does not have js.node, then that documentation includes/suggests/automatically uses Chocolatey.  

For example, I tested the installation on a clean desktop with only Anaconda installed.  The js.node installation step included install visualstudio2017, python3 update, and chocolatey

- [ ] Add time estimate and a few options and assumptions

- [ ] Add recommendation to install on a machine where updates are not going to break the environment for other uses. Or add recommendation for level of expertise suggested.    Should only professionals developers test? or can anyone with basic software development expertise ? (this install would ruin their environment and they may or may not have multiple options).

**Comment by ChristinaB** [comment]
![image](https://user-images.githubusercontent.com/4108369/80025268-3442ad80-8495-11ea-888b-6031d1542ada.png)
Can I use Chocolatey? Why Yarn?

**Comment by ChristinaB** [comment]
- [ ] Add details on the install for clean environments and new developers with requirements such as Install Github and Install Anaconda  with hyperlinks to source of install instructions. 

- [ ] Clarify that these are Windows install steps.  

- [ ] Update that the installation instructions should be from a CMD prompt and not a Bash prompt (the different terminal views sometimes work for some jobs, sometime not).   e.g.  the Yarn install step ONLY works from CMD prompt (which I never usually use).

**Comment by ChristinaB** [comment]
- [ ] Update `cd backend`   to `cd ../backend` assuming the user/tester is running the steps sequentially OR don't put it in a code box and just tell the user to change directory to the backend folder.

**Comment by ChristinaB** [comment]
` sudo apt install python3 python3-pip`  instructions should live in another page names something like - how to update your computer to Python3.md -  
let's assume that everyone has Python 3  
- also- the sudo feature on Windows is a pain to install and use
- the Linus/UNIX environment setup on a Git Bash or Cygwin terminal  - on a Windows machine is confusing. 

- [ ] Add gedit to the list of programs to install

**Comment by ChristinaB** [comment]
@sblack-usu @Castronova This is where we can discuss making sure this works for working with private resources

**Comment by ChristinaB** [comment]
This should also work in the CUAHSI Jupyter Hub cloud or any JH with credentials to use private resources.

**Comment by sblack-usu** [comment]
Is desktop installation a path we even want to support?  I wonder if we could extend the sync project to give a user the ability to manage multiple jupyterhubs in one deploy.  This way, we could host the sync app and manage their registered jupyterhubs from the deploy.  

As for private resources, maybe I'm not clear on everything.  But I thought the hurdle was private resources to Binder... which will always be an issue with official builds of Binder (at least until they add authentication, which I doubt they have any plans for).  I also don't think the sync app should be used with Binder because the idea behind Binder is to be temporary.  The sync app is for managing resources on jupyter deployments that persist.

As I'm writing this, I guess I can see an argument for a Desktop installation of sync next to a local deploy of jupyterhub.  I'm not clear on all the use cases here.

**Comment by kylecombes** [comment]
@Castronova and I are working on simplifying the installation process for non-developers on the branch tony/packaging. I've already removed the Node installation component. It should be entirely installable using only `pip install` or `conda install` shortly.

**Comment by aaraney** [comment]
closing as this has been resolved in new versions of the software. see [installation guide](https://github.com/hydroshare/hydroshare_on_jupyter/blob/master/README.md#installation).
